[package]
name = "minimal-compiler"
version = "0.1.0"
edition = "2021"
description = "The Minimal programming language compiler."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]